/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "index",
      className: "sidebar-introduction",
    },
    {
      type: "category",
      label: "Getting Started",
      className: "sidebar-getting-started",
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
  ],
  apiSidebar: [
    {
      type: "doc",
      id: "reference/introduction",
      className: "sidebar-reference-introduction",
    },
    {
      type: "category",
      label: "NFT API",
      className: "sidebar-nft-api",
      items: ["reference/get-nfts-by-wallet"],
    },
  ]
};

module.exports = sidebars;
